version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5555:5432"
    expose:
      - "5555"
  express:
    build:
      context: .
    links:
      - postgres
    ports:
      - "80:3000"
    expose:
      - "80"
